import groovy.util.Node
import groovy.util.NodeList
import groovy.xml.XmlNodePrinter
import groovy.xml.XmlParser
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Post-processes the merged manifest for a single extension flavor: sets the package
 * name, records the KSP-generated Extension class, and adds any deep-link intent filters.
 * Wired via the AGP Variant API's SingleArtifact.MERGED_MANIFEST transform (replaces the
 * old internal applicationVariants/ProcessMultiApkApplicationManifest hook removed in AGP 9).
 */
@CacheableTask
abstract class ExtensionManifestTask : DefaultTask() {

    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val mergedManifest: RegularFileProperty

    @get:OutputFile
    abstract val updatedManifest: RegularFileProperty

    @get:Input
    abstract val applicationId: Property<String>

    @get:Input
    abstract val deepLinkSchemes: ListProperty<String>

    @get:Input
    abstract val deepLinkHosts: ListProperty<String>

    @get:Input
    abstract val deepLinkPathPatterns: ListProperty<String>

    @get:Input
    abstract val deepLinkPaths: ListProperty<String>

    @TaskAction
    fun run() {
        val manifestFile = mergedManifest.get().asFile
        if (!manifestFile.exists()) {
            throw GradleException("Can't find merged manifest at ${manifestFile.path}")
        }

        val extClass = "tachiyomix.extension.Extension" // This class is generated by ksp
        val parser = XmlParser().parse(manifestFile)

        // Replace the package name
        parser.attributes()["package"] = applicationId.get()

        val app = (parser["application"] as NodeList).first() as Node

        // Add source class metadata
        Node(
            app, "meta-data",
            mapOf(
                "android:name" to "source.class",
                "android:value" to extClass
            )
        )

        val hosts = deepLinkHosts.get()
        if (hosts.isNotEmpty()) {
            addDeepLinks(
                app,
                schemes = deepLinkSchemes.get(),
                hosts = hosts,
                pathPatterns = deepLinkPathPatterns.get(),
                paths = deepLinkPaths.get(),
            )
        }

        val outFile = updatedManifest.get().asFile
        outFile.parentFile.mkdirs()
        XmlNodePrinter(outFile.printWriter()).print(parser)
    }

    private fun addDeepLinks(
        app: Node,
        schemes: List<String>,
        hosts: List<String>,
        pathPatterns: List<String>,
        paths: List<String>,
    ) {
        val activity = Node(
            app, "activity",
            mapOf(
                "android:name" to "tachiyomix.deeplink.SourceDeepLinkActivity",
                "android:exported" to "true",
                "android:theme" to "@android:style/Theme.NoDisplay"
            )
        )

        val filter = Node(activity, "intent-filter")
        Node(filter, "action", mapOf("android:name" to "android.intent.action.VIEW"))
        Node(filter, "category", mapOf("android:name" to "android.intent.category.DEFAULT"))
        Node(filter, "category", mapOf("android:name" to "android.intent.category.BROWSABLE"))

        hosts.indices.forEach { i ->
            val data = mutableMapOf<String, String>()
            schemes.getOrNull(i)?.takeIf { it.isNotEmpty() }?.let { data["android:scheme"] = it }
            hosts.getOrNull(i)?.takeIf { it.isNotEmpty() }?.let { data["android:host"] = it }
            pathPatterns.getOrNull(i)?.takeIf { it.isNotEmpty() }?.let { data["android:pathPattern"] = it }
            paths.getOrNull(i)?.takeIf { it.isNotEmpty() }?.let { data["android:path"] = it }
            Node(filter, "data", data)
        }
    }
}
